# Generated by Django 5.1 on 2024-08-15 10:48

import django.db.models.deletion
import theatre_api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre_api", "0003_ticket_reservation_alter_reservation_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="theatrehall",
            options={"verbose_name_plural": "theatre halls"},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="actor",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=theatre_api.models.create_custom_path
            ),
        ),
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=theatre_api.models.create_custom_path
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("performance", "row", "seat")},
        ),
        migrations.AddIndex(
            model_name="performance",
            index=models.Index(
                fields=["play", "theatre_hall"], name="theatre_api_play_id_b4e39b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="performance",
            index=models.Index(
                fields=["show_time"], name="theatre_api_show_ti_2c4c5b_idx"
            ),
        ),
    ]
